version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mountify
      POSTGRES_USER: mountify
      POSTGRES_PASSWORD: mountify
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  app:
    build: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://mountify:mountify@postgres:5432/mountify
    ports:
      - "3000:3000"
    depends_on:
      - postgres