# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - BASE_URL=http://localhost
      - MOUNTIFY_PORT=3000
      - PG_URL=postgres://<YourUserName>:<YourPassword>@mountify-postgres-container:5432/<YourDatabaseName>
      - JWT_SECRET="<YourJwtSecret>"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: <YourDatabaseName>
      POSTGRES_USER: <YourUserName>
      POSTGRES_PASSWORD: <YourPassword>
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/initdb:/docker-entrypoint-initdb.d
      
volumes:
  db-data: