BEGIN;

DROP TABLE IF EXISTS "user_planned_mountain";
DROP TABLE IF EXISTS "user_visited_mountain";
DROP TABLE IF EXISTS "country_has_region";
DROP TABLE IF EXISTS "mountain_has_species";
DROP TABLE IF EXISTS "mountain";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "region";
DROP TABLE IF EXISTS "country";
DROP TABLE IF EXISTS "species";

CREATE TABLE "species"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "name" VARCHAR(50),
   "type" SMALLINT, -- 0: Fauna, 1: Flora
   "description" TEXT,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ
);

CREATE TABLE "country"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "name" VARCHAR(50),
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ
);

CREATE TABLE "region"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "name" VARCHAR(50),
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "username" VARCHAR(50),
   "email" VARCHAR(50),
   "password_hash" VARCHAR(255),
   "picture" VARCHAR(255),
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ
);

CREATE TABLE "mountain"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "name" VARCHAR(50),
   "latitude" DECIMAL(15,6),
   "longitude" DECIMAL(15,6),
   "altitude" INT,
   "description" TEXT,
   "picture" VARCHAR(255),
   "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
   "country_id" INTEGER NOT NULL REFERENCES "country"("id") ON DELETE CASCADE,
   "region_id" INTEGER NOT NULL REFERENCES "region"("id") ON DELETE CASCADE,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ
);

CREATE TABLE "mountain_has_species"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "mountain_id" INTEGER NOT NULL REFERENCES "mountain"("id") ON DELETE CASCADE,
   "species_id" INTEGER NOT NULL REFERENCES "species"("id") ON DELETE CASCADE,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ,

   UNIQUE("mountain_id", "species_id")
);

CREATE TABLE "country_has_region"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "country_id" INTEGER NOT NULL REFERENCES "country"("id") ON DELETE CASCADE,
   "region_id" INTEGER NOT NULL REFERENCES "region"("id") ON DELETE CASCADE,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ,

   UNIQUE("country_id", "region_id")
);

CREATE TABLE "user_visited_mountain"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "mountain_id" INTEGER NOT NULL REFERENCES "mountain"("id") ON DELETE CASCADE,
   "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ,

   UNIQUE("mountain_id", "user_id")
);

CREATE TABLE "user_planned_mountain"(
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "mountain_id" INTEGER NOT NULL REFERENCES "mountain"("id") ON DELETE CASCADE,
   "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ,

   UNIQUE("mountain_id", "user_id")
);

COMMIT;